/*jslint */
/*global AdobeEdge: false, window: false, document: false, console:false, alert: false */
(function (compId) {

    "use strict";
    var im='images/',
        aud='media/',
        vid='media/',
        js='js/',
        fonts = {
        },
        opts = {
            'gAudioPreloadPreference': 'auto',
            'gVideoPreloadPreference': 'auto'
        },
        resources = [
        ],
        scripts = [
        ],
        symbols = {
            "stage": {
                version: "6.0.0",
                minimumCompatibleVersion: "5.0.0",
                build: "6.0.0.400",
                scaleToFit: "none",
                centerStage: "none",
                resizeInstances: false,
                content: {
                    dom: [
                        {
                            id: 'worker_green',
                            type: 'image',
                            rect: ['323', '284', '15px', '16px', 'auto', 'auto'],
                            opacity: '1',
                            fill: ["rgba(0,0,0,0)",im+"worker_green.svg",'0px','0px'],
                            filter: [0, 0, 1, 1, 0, 0, 0, 0, "rgba(0,0,0,0)", 0, 0, 0],
                            transform: [[],[],[],['0','0']]
                        },
                        {
                            id: 'Wave22',
                            type: 'image',
                            rect: ['311px', '271px', '40px', '42px', 'auto', 'auto'],
                            fill: ["rgba(0,0,0,0)",im+"Wave2.svg",'0px','0px']
                        },
                        {
                            id: 'Wave22Copy',
                            type: 'image',
                            rect: ['311px', '271px', '40px', '42px', 'auto', 'auto'],
                            fill: ["rgba(0,0,0,0)",im+"Wave2.svg",'0px','0px']
                        },
                        {
                            id: 'Wave22Copy2',
                            type: 'image',
                            rect: ['311px', '271px', '40px', '42px', 'auto', 'auto'],
                            fill: ["rgba(0,0,0,0)",im+"Wave2.svg",'0px','0px']
                        }
                    ],
                    style: {
                        '${Stage}': {
                            isStage: true,
                            rect: ['null', 'null', '550px', '400px', 'auto', 'auto'],
                            overflow: 'hidden',
                            fill: ["rgba(0,0,0,1.00)"]
                        }
                    }
                },
                timeline: {
                    duration: 23372.923529809,
                    autoPlay: true,
                    data: [
                        [
                            "eid123",
                            "filter.saturate",
                            14041,
                            656,
                            "easeOutBack",
                            "${worker_green}",
                            '1',
                            '0'
                        ],
                        [
                            "eid151",
                            "filter.saturate",
                            14697,
                            731,
                            "easeOutBack",
                            "${worker_green}",
                            '0',
                            '1'
                        ],
                        [
                            "eid156",
                            "filter.saturate",
                            15427,
                            458,
                            "easeOutBack",
                            "${worker_green}",
                            '1',
                            '0'
                        ],
                        [
                            "eid157",
                            "filter.saturate",
                            15885,
                            603,
                            "easeOutBack",
                            "${worker_green}",
                            '0',
                            '1'
                        ],
                        [
                            "eid166",
                            "filter.saturate",
                            16488,
                            739,
                            "easeOutBack",
                            "${worker_green}",
                            '1',
                            '0'
                        ],
                        [
                            "eid167",
                            "filter.saturate",
                            17227,
                            511,
                            "easeOutBack",
                            "${worker_green}",
                            '0',
                            '1'
                        ],
                        [
                            "eid168",
                            "filter.saturate",
                            17738,
                            708,
                            "easeOutBack",
                            "${worker_green}",
                            '1',
                            '0'
                        ],
                        [
                            "eid169",
                            "filter.saturate",
                            18447,
                            542,
                            "easeOutBack",
                            "${worker_green}",
                            '0',
                            '1'
                        ],
                        [
                            "eid264",
                            "top",
                            14041,
                            0,
                            "linear",
                            "${Wave22Copy}",
                            '271px',
                            '271px'
                        ],
                        [
                            "eid296",
                            "top",
                            14177,
                            0,
                            "linear",
                            "${Wave22Copy2}",
                            '271px',
                            '271px'
                        ],
                        [
                            "eid285",
                            "opacity",
                            14041,
                            870,
                            "linear",
                            "${Wave22Copy}",
                            '1',
                            '0'
                        ],
                        [
                            "eid286",
                            "opacity",
                            15291,
                            870,
                            "linear",
                            "${Wave22Copy}",
                            '1',
                            '0'
                        ],
                        [
                            "eid287",
                            "opacity",
                            16541,
                            870,
                            "linear",
                            "${Wave22Copy}",
                            '1',
                            '0'
                        ],
                        [
                            "eid288",
                            "opacity",
                            17791,
                            870,
                            "linear",
                            "${Wave22Copy}",
                            '1',
                            '0'
                        ],
                        [
                            "eid245",
                            "scaleY",
                            1041,
                            1061,
                            "linear",
                            "${Wave22}",
                            '0',
                            '1.5'
                        ],
                        [
                            "eid246",
                            "scaleY",
                            2291,
                            1061,
                            "linear",
                            "${Wave22}",
                            '0.2',
                            '1.5'
                        ],
                        [
                            "eid247",
                            "scaleY",
                            3541,
                            1061,
                            "linear",
                            "${Wave22}",
                            '0.2',
                            '1.5'
                        ],
                        [
                            "eid248",
                            "scaleY",
                            4791,
                            1061,
                            "linear",
                            "${Wave22}",
                            '0.2',
                            '1.5'
                        ],
                        [
                            "eid249",
                            "scaleY",
                            6041,
                            1061,
                            "linear",
                            "${Wave22}",
                            '0.2',
                            '1.5'
                        ],
                        [
                            "eid250",
                            "scaleY",
                            7291,
                            1061,
                            "linear",
                            "${Wave22}",
                            '0',
                            '1.5'
                        ],
                        [
                            "eid251",
                            "scaleY",
                            8541,
                            1061,
                            "linear",
                            "${Wave22}",
                            '0.2',
                            '1.5'
                        ],
                        [
                            "eid252",
                            "scaleY",
                            9791,
                            1061,
                            "linear",
                            "${Wave22}",
                            '0.2',
                            '1.5'
                        ],
                        [
                            "eid253",
                            "scaleY",
                            11041,
                            1061,
                            "linear",
                            "${Wave22}",
                            '0.2',
                            '1.5'
                        ],
                        [
                            "eid254",
                            "scaleY",
                            12291,
                            1061,
                            "linear",
                            "${Wave22}",
                            '0.2',
                            '1.5'
                        ],
                        [
                            "eid329",
                            "scaleY",
                            19541,
                            1061,
                            "linear",
                            "${Wave22}",
                            '0',
                            '1.5'
                        ],
                        [
                            "eid330",
                            "scaleY",
                            20791,
                            1061,
                            "linear",
                            "${Wave22}",
                            '0.2',
                            '1.5'
                        ],
                        [
                            "eid331",
                            "scaleY",
                            22041,
                            1061,
                            "linear",
                            "${Wave22}",
                            '0.2',
                            '1.5'
                        ],
                        [
                            "eid260",
                            "left",
                            1041,
                            0,
                            "linear",
                            "${Wave22}",
                            '311px',
                            '311px'
                        ],
                        [
                            "eid359",
                            "left",
                            19541,
                            0,
                            "linear",
                            "${Wave22}",
                            '311px',
                            '311px'
                        ],
                        [
                            "eid295",
                            "left",
                            14041,
                            0,
                            "linear",
                            "${Wave22Copy}",
                            '311px',
                            '311px'
                        ],
                        [
                            "eid317",
                            "opacity",
                            14177,
                            870,
                            "linear",
                            "${Wave22Copy2}",
                            '1',
                            '0'
                        ],
                        [
                            "eid318",
                            "opacity",
                            15427,
                            870,
                            "linear",
                            "${Wave22Copy2}",
                            '1',
                            '0'
                        ],
                        [
                            "eid319",
                            "opacity",
                            16677,
                            870,
                            "linear",
                            "${Wave22Copy2}",
                            '1',
                            '0'
                        ],
                        [
                            "eid320",
                            "opacity",
                            17927,
                            870,
                            "linear",
                            "${Wave22Copy2}",
                            '1',
                            '0'
                        ],
                        [
                            "eid29",
                            "scaleY",
                            1041,
                            351,
                            "easeOutBack",
                            "${worker_green}",
                            '0',
                            '1'
                        ],
                        [
                            "eid130",
                            "scaleY",
                            14041,
                            656,
                            "easeOutBack",
                            "${worker_green}",
                            '1',
                            '1.2'
                        ],
                        [
                            "eid131",
                            "scaleY",
                            14697,
                            731,
                            "easeOutBack",
                            "${worker_green}",
                            '1.2',
                            '1'
                        ],
                        [
                            "eid154",
                            "scaleY",
                            15427,
                            458,
                            "easeOutBack",
                            "${worker_green}",
                            '1',
                            '1.2'
                        ],
                        [
                            "eid155",
                            "scaleY",
                            15885,
                            603,
                            "easeOutBack",
                            "${worker_green}",
                            '1.2',
                            '1'
                        ],
                        [
                            "eid162",
                            "scaleY",
                            16488,
                            739,
                            "easeOutBack",
                            "${worker_green}",
                            '1',
                            '1.2'
                        ],
                        [
                            "eid163",
                            "scaleY",
                            17227,
                            511,
                            "easeOutBack",
                            "${worker_green}",
                            '1.2',
                            '1'
                        ],
                        [
                            "eid164",
                            "scaleY",
                            17738,
                            708,
                            "easeOutBack",
                            "${worker_green}",
                            '1',
                            '1.2'
                        ],
                        [
                            "eid165",
                            "scaleY",
                            18447,
                            542,
                            "easeOutBack",
                            "${worker_green}",
                            '1.2',
                            '1'
                        ],
                        [
                            "eid365",
                            "scaleY",
                            23102,
                            271,
                            "easeInBack",
                            "${worker_green}",
                            '1',
                            '0'
                        ],
                        [
                            "eid265",
                            "scaleY",
                            14041,
                            1061,
                            "linear",
                            "${Wave22Copy}",
                            '0',
                            '1.5'
                        ],
                        [
                            "eid266",
                            "scaleY",
                            15291,
                            1061,
                            "linear",
                            "${Wave22Copy}",
                            '0.2',
                            '1.5'
                        ],
                        [
                            "eid267",
                            "scaleY",
                            16541,
                            1061,
                            "linear",
                            "${Wave22Copy}",
                            '0.2',
                            '1.5'
                        ],
                        [
                            "eid268",
                            "scaleY",
                            17791,
                            1061,
                            "linear",
                            "${Wave22Copy}",
                            '0.2',
                            '1.5'
                        ],
                        [
                            "eid327",
                            "left",
                            14177,
                            0,
                            "linear",
                            "${Wave22Copy2}",
                            '311px',
                            '311px'
                        ],
                        [
                            "eid28",
                            "scaleX",
                            1041,
                            351,
                            "easeOutBack",
                            "${worker_green}",
                            '0',
                            '1'
                        ],
                        [
                            "eid128",
                            "scaleX",
                            14041,
                            656,
                            "easeOutBack",
                            "${worker_green}",
                            '1',
                            '1.2'
                        ],
                        [
                            "eid129",
                            "scaleX",
                            14697,
                            731,
                            "easeOutBack",
                            "${worker_green}",
                            '1.2',
                            '1'
                        ],
                        [
                            "eid152",
                            "scaleX",
                            15427,
                            458,
                            "easeOutBack",
                            "${worker_green}",
                            '1',
                            '1.2'
                        ],
                        [
                            "eid153",
                            "scaleX",
                            15885,
                            603,
                            "easeOutBack",
                            "${worker_green}",
                            '1.2',
                            '1'
                        ],
                        [
                            "eid158",
                            "scaleX",
                            16488,
                            739,
                            "easeOutBack",
                            "${worker_green}",
                            '1',
                            '1.2'
                        ],
                        [
                            "eid159",
                            "scaleX",
                            17227,
                            511,
                            "easeOutBack",
                            "${worker_green}",
                            '1.2',
                            '1'
                        ],
                        [
                            "eid160",
                            "scaleX",
                            17738,
                            708,
                            "easeOutBack",
                            "${worker_green}",
                            '1',
                            '1.2'
                        ],
                        [
                            "eid161",
                            "scaleX",
                            18447,
                            542,
                            "easeOutBack",
                            "${worker_green}",
                            '1.2',
                            '1'
                        ],
                        [
                            "eid364",
                            "scaleX",
                            23102,
                            271,
                            "easeInBack",
                            "${worker_green}",
                            '1',
                            '0'
                        ],
                        [
                            "eid307",
                            "scaleX",
                            14177,
                            1061,
                            "linear",
                            "${Wave22Copy2}",
                            '0',
                            '1.5'
                        ],
                        [
                            "eid308",
                            "scaleX",
                            15427,
                            1061,
                            "linear",
                            "${Wave22Copy2}",
                            '0.2',
                            '1.5'
                        ],
                        [
                            "eid309",
                            "scaleX",
                            16677,
                            1061,
                            "linear",
                            "${Wave22Copy2}",
                            '0.2',
                            '1.5'
                        ],
                        [
                            "eid310",
                            "scaleX",
                            17927,
                            1061,
                            "linear",
                            "${Wave22Copy2}",
                            '0.2',
                            '1.5'
                        ],
                        [
                            "eid2",
                            "background-color",
                            0,
                            0,
                            "linear",
                            "${Stage}",
                            'rgba(0,0,0,1.00)',
                            'rgba(0,0,0,1.00)'
                        ],
                        [
                            "eid263",
                            "top",
                            1041,
                            0,
                            "linear",
                            "${Wave22}",
                            '271px',
                            '271px'
                        ],
                        [
                            "eid328",
                            "top",
                            19541,
                            0,
                            "linear",
                            "${Wave22}",
                            '271px',
                            '271px'
                        ],
                        [
                            "eid215",
                            "scaleX",
                            1041,
                            1061,
                            "linear",
                            "${Wave22}",
                            '0',
                            '1.5'
                        ],
                        [
                            "eid216",
                            "scaleX",
                            2291,
                            1061,
                            "linear",
                            "${Wave22}",
                            '0.2',
                            '1.5'
                        ],
                        [
                            "eid217",
                            "scaleX",
                            3541,
                            1061,
                            "linear",
                            "${Wave22}",
                            '0.2',
                            '1.5'
                        ],
                        [
                            "eid218",
                            "scaleX",
                            4791,
                            1061,
                            "linear",
                            "${Wave22}",
                            '0.2',
                            '1.5'
                        ],
                        [
                            "eid219",
                            "scaleX",
                            6041,
                            1061,
                            "linear",
                            "${Wave22}",
                            '0.2',
                            '1.5'
                        ],
                        [
                            "eid220",
                            "scaleX",
                            7291,
                            1061,
                            "linear",
                            "${Wave22}",
                            '0',
                            '1.5'
                        ],
                        [
                            "eid221",
                            "scaleX",
                            8541,
                            1061,
                            "linear",
                            "${Wave22}",
                            '0.2',
                            '1.5'
                        ],
                        [
                            "eid222",
                            "scaleX",
                            9791,
                            1061,
                            "linear",
                            "${Wave22}",
                            '0.2',
                            '1.5'
                        ],
                        [
                            "eid223",
                            "scaleX",
                            11041,
                            1061,
                            "linear",
                            "${Wave22}",
                            '0.2',
                            '1.5'
                        ],
                        [
                            "eid224",
                            "scaleX",
                            12291,
                            1061,
                            "linear",
                            "${Wave22}",
                            '0.2',
                            '1.5'
                        ],
                        [
                            "eid339",
                            "scaleX",
                            19541,
                            1061,
                            "linear",
                            "${Wave22}",
                            '0',
                            '1.5'
                        ],
                        [
                            "eid340",
                            "scaleX",
                            20791,
                            1061,
                            "linear",
                            "${Wave22}",
                            '0.2',
                            '1.5'
                        ],
                        [
                            "eid341",
                            "scaleX",
                            22041,
                            1061,
                            "linear",
                            "${Wave22}",
                            '0.2',
                            '1.5'
                        ],
                        [
                            "eid225",
                            "opacity",
                            1041,
                            870,
                            "linear",
                            "${Wave22}",
                            '1',
                            '0'
                        ],
                        [
                            "eid227",
                            "opacity",
                            2291,
                            870,
                            "linear",
                            "${Wave22}",
                            '1',
                            '0'
                        ],
                        [
                            "eid229",
                            "opacity",
                            3541,
                            870,
                            "linear",
                            "${Wave22}",
                            '1',
                            '0'
                        ],
                        [
                            "eid231",
                            "opacity",
                            4791,
                            870,
                            "linear",
                            "${Wave22}",
                            '1',
                            '0'
                        ],
                        [
                            "eid233",
                            "opacity",
                            6041,
                            870,
                            "linear",
                            "${Wave22}",
                            '1',
                            '0'
                        ],
                        [
                            "eid235",
                            "opacity",
                            7291,
                            870,
                            "linear",
                            "${Wave22}",
                            '1',
                            '0'
                        ],
                        [
                            "eid237",
                            "opacity",
                            8541,
                            870,
                            "linear",
                            "${Wave22}",
                            '1',
                            '0'
                        ],
                        [
                            "eid239",
                            "opacity",
                            9791,
                            870,
                            "linear",
                            "${Wave22}",
                            '1',
                            '0'
                        ],
                        [
                            "eid241",
                            "opacity",
                            11041,
                            870,
                            "linear",
                            "${Wave22}",
                            '1',
                            '0'
                        ],
                        [
                            "eid243",
                            "opacity",
                            12291,
                            870,
                            "linear",
                            "${Wave22}",
                            '1',
                            '0'
                        ],
                        [
                            "eid349",
                            "opacity",
                            19541,
                            870,
                            "linear",
                            "${Wave22}",
                            '1',
                            '0'
                        ],
                        [
                            "eid350",
                            "opacity",
                            20791,
                            870,
                            "linear",
                            "${Wave22}",
                            '1',
                            '0'
                        ],
                        [
                            "eid351",
                            "opacity",
                            22041,
                            870,
                            "linear",
                            "${Wave22}",
                            '1',
                            '0'
                        ],
                        [
                            "eid275",
                            "scaleX",
                            14041,
                            1061,
                            "linear",
                            "${Wave22Copy}",
                            '0',
                            '1.5'
                        ],
                        [
                            "eid276",
                            "scaleX",
                            15291,
                            1061,
                            "linear",
                            "${Wave22Copy}",
                            '0.2',
                            '1.5'
                        ],
                        [
                            "eid277",
                            "scaleX",
                            16541,
                            1061,
                            "linear",
                            "${Wave22Copy}",
                            '0.2',
                            '1.5'
                        ],
                        [
                            "eid278",
                            "scaleX",
                            17791,
                            1061,
                            "linear",
                            "${Wave22Copy}",
                            '0.2',
                            '1.5'
                        ],
                        [
                            "eid297",
                            "scaleY",
                            14177,
                            1061,
                            "linear",
                            "${Wave22Copy2}",
                            '0',
                            '1.5'
                        ],
                        [
                            "eid298",
                            "scaleY",
                            15427,
                            1061,
                            "linear",
                            "${Wave22Copy2}",
                            '0.2',
                            '1.5'
                        ],
                        [
                            "eid299",
                            "scaleY",
                            16677,
                            1061,
                            "linear",
                            "${Wave22Copy2}",
                            '0.2',
                            '1.5'
                        ],
                        [
                            "eid300",
                            "scaleY",
                            17927,
                            1061,
                            "linear",
                            "${Wave22Copy2}",
                            '0.2',
                            '1.5'
                        ]
                    ]
                }
            }
        };

    AdobeEdge.registerCompositionDefn(compId, symbols, fonts, scripts, resources, opts);

    if (!window.edge_authoring_mode) AdobeEdge.getComposition(compId).load("animation_edgeActions.js");
})("EDGE-840678496");
